# Generated by Django 5.0.4 on 2024-04-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('body', models.CharField(max_length=255, unique=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
